---
networks:
  api_network:
    driver: bridge

volumes:
  traefik_certs:

services:
  formsubmitterapi:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: formsubmitterapi
    networks:
      - api_network
    expose:
      - 5000
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.formsubmitterapi.rule=Host(`flux.milesguard.com`)"
      - "traefik.http.routers.formsubmitterapi.entrypoints=websecure"
      - "traefik.http.routers.formsubmitterapi.tls=true"
      - "traefik.http.routers.formsubmitterapi.tls.certresolver=formsubmitterresolver"
      - "traefik.http.services.formsubmitterapi.loadbalancer.server.port=5000"
      - "traefik.http.services.formsubmitterapi.loadbalancer.server.scheme=http"
    volumes:
      - ./formsubmitter_api.py:/app/formsubmitter_api.py
    environment:
      SMTP_SERVER: ${SMTP_SERVER}
      SMTP_PORT: ${SMTP_PORT}
      SMTP_TIMEOUT: ${SMTP_TIMEOUT}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
      TO_EMAIL: ${TO_EMAIL}
    command: sh -c "gunicorn -w 8 -b 0.0.0.0:5000 formsubmitter_api:app"
    restart: always
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:5000/health || exit 1"]
      interval: 1m
      timeout: 10s
      retries: 3

  traefik:
    image: traefik:latest
    container_name: traefik-formsubmitter
    command:
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.network=api_network"
      - "--certificatesresolvers.formsubmitterresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.formsubmitterresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.formsubmitterresolver.acme.email=${ACME_EMAIL}"
      - "--certificatesresolvers.formsubmitterresolver.acme.storage=/acme.json"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.web.address=:80"
    ports:
      - "443:443"
      - "80:80"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik/acme.json:/acme.json
      - traefik_certs:/etc/traefik/certs
    networks:
      - api_network
    labels:
      - "traefik.http.middlewares.cors.headers.accesscontrolalloworigin=*"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowmethods=GET,POST,OPTIONS"
      - "traefik.http.middlewares.cors.headers.accesscontrolallowheaders=Content-Type"
      - "traefik.http.middlewares.cors.headers.accesscontrolexposeheaders=Content-Length,Content-Type"
    restart: unless-stopped
